#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="XAY_DUNG_MAIL_SERVER")]
	public partial class dbMailServerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN_MAIL(ADMIN_MAIL instance);
    partial void UpdateADMIN_MAIL(ADMIN_MAIL instance);
    partial void DeleteADMIN_MAIL(ADMIN_MAIL instance);
    partial void InsertTRANG_THAI(TRANG_THAI instance);
    partial void UpdateTRANG_THAI(TRANG_THAI instance);
    partial void DeleteTRANG_THAI(TRANG_THAI instance);
    partial void InsertDANHSACH_MAIL(DANHSACH_MAIL instance);
    partial void UpdateDANHSACH_MAIL(DANHSACH_MAIL instance);
    partial void DeleteDANHSACH_MAIL(DANHSACH_MAIL instance);
    partial void InsertDOMAIN_MAIL(DOMAIN_MAIL instance);
    partial void UpdateDOMAIN_MAIL(DOMAIN_MAIL instance);
    partial void DeleteDOMAIN_MAIL(DOMAIN_MAIL instance);
    partial void InsertMATKHAU_LOCAL(MATKHAU_LOCAL instance);
    partial void UpdateMATKHAU_LOCAL(MATKHAU_LOCAL instance);
    partial void DeleteMATKHAU_LOCAL(MATKHAU_LOCAL instance);
    partial void InsertMATKHAU_MAIL(MATKHAU_MAIL instance);
    partial void UpdateMATKHAU_MAIL(MATKHAU_MAIL instance);
    partial void DeleteMATKHAU_MAIL(MATKHAU_MAIL instance);
    partial void InsertNOIDUNG_MAIL(NOIDUNG_MAIL instance);
    partial void UpdateNOIDUNG_MAIL(NOIDUNG_MAIL instance);
    partial void DeleteNOIDUNG_MAIL(NOIDUNG_MAIL instance);
    partial void InsertTHONGTIN_CLIENT(THONGTIN_CLIENT instance);
    partial void UpdateTHONGTIN_CLIENT(THONGTIN_CLIENT instance);
    partial void DeleteTHONGTIN_CLIENT(THONGTIN_CLIENT instance);
    #endregion
		
		public dbMailServerDataContext() : 
				base(global::MailServer.Properties.Settings.Default.XAY_DUNG_MAIL_SERVERConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbMailServerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMailServerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMailServerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbMailServerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN_MAIL> ADMIN_MAILs
		{
			get
			{
				return this.GetTable<ADMIN_MAIL>();
			}
		}
		
		public System.Data.Linq.Table<TRANG_THAI> TRANG_THAIs
		{
			get
			{
				return this.GetTable<TRANG_THAI>();
			}
		}
		
		public System.Data.Linq.Table<DANHSACH_MAIL> DANHSACH_MAILs
		{
			get
			{
				return this.GetTable<DANHSACH_MAIL>();
			}
		}
		
		public System.Data.Linq.Table<DOMAIN_MAIL> DOMAIN_MAILs
		{
			get
			{
				return this.GetTable<DOMAIN_MAIL>();
			}
		}
		
		public System.Data.Linq.Table<MATKHAU_LOCAL> MATKHAU_LOCALs
		{
			get
			{
				return this.GetTable<MATKHAU_LOCAL>();
			}
		}
		
		public System.Data.Linq.Table<MATKHAU_MAIL> MATKHAU_MAILs
		{
			get
			{
				return this.GetTable<MATKHAU_MAIL>();
			}
		}
		
		public System.Data.Linq.Table<NOIDUNG_MAIL> NOIDUNG_MAILs
		{
			get
			{
				return this.GetTable<NOIDUNG_MAIL>();
			}
		}
		
		public System.Data.Linq.Table<THONGTIN_CLIENT> THONGTIN_CLIENTs
		{
			get
			{
				return this.GetTable<THONGTIN_CLIENT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN_MAIL")]
	public partial class ADMIN_MAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_ADMIN_MAIL;
		
		private string _USERNAMEAD;
		
		private string _PASSWORDAD;
		
		private string _HO;
		
		private string _TEN;
		
		private string _NTNS;
		
		private string _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_ADMIN_MAILChanging(string value);
    partial void Onid_ADMIN_MAILChanged();
    partial void OnUSERNAMEADChanging(string value);
    partial void OnUSERNAMEADChanged();
    partial void OnPASSWORDADChanging(string value);
    partial void OnPASSWORDADChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnNTNSChanging(string value);
    partial void OnNTNSChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    #endregion
		
		public ADMIN_MAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ADMIN_MAIL", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_ADMIN_MAIL
		{
			get
			{
				return this._id_ADMIN_MAIL;
			}
			set
			{
				if ((this._id_ADMIN_MAIL != value))
				{
					this.Onid_ADMIN_MAILChanging(value);
					this.SendPropertyChanging();
					this._id_ADMIN_MAIL = value;
					this.SendPropertyChanged("id_ADMIN_MAIL");
					this.Onid_ADMIN_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAMEAD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USERNAMEAD
		{
			get
			{
				return this._USERNAMEAD;
			}
			set
			{
				if ((this._USERNAMEAD != value))
				{
					this.OnUSERNAMEADChanging(value);
					this.SendPropertyChanging();
					this._USERNAMEAD = value;
					this.SendPropertyChanged("USERNAMEAD");
					this.OnUSERNAMEADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORDAD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORDAD
		{
			get
			{
				return this._PASSWORDAD;
			}
			set
			{
				if ((this._PASSWORDAD != value))
				{
					this.OnPASSWORDADChanging(value);
					this.SendPropertyChanging();
					this._PASSWORDAD = value;
					this.SendPropertyChanged("PASSWORDAD");
					this.OnPASSWORDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NTNS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NTNS
		{
			get
			{
				return this._NTNS;
			}
			set
			{
				if ((this._NTNS != value))
				{
					this.OnNTNSChanging(value);
					this.SendPropertyChanging();
					this._NTNS = value;
					this.SendPropertyChanged("NTNS");
					this.OnNTNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANG_THAI")]
	public partial class TRANG_THAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_TRANG_THAI;
		
		private System.Nullable<bool> _DANHDAU;
		
		private System.Nullable<bool> _XOATHU;
		
		private System.Nullable<bool> _STATUS_MAIL;
		
		private System.Nullable<System.DateTime> _UPDATE_TIME_MAIL;
		
		private EntitySet<NOIDUNG_MAIL> _NOIDUNG_MAILs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_TRANG_THAIChanging(string value);
    partial void Onid_TRANG_THAIChanged();
    partial void OnDANHDAUChanging(System.Nullable<bool> value);
    partial void OnDANHDAUChanged();
    partial void OnXOATHUChanging(System.Nullable<bool> value);
    partial void OnXOATHUChanged();
    partial void OnSTATUS_MAILChanging(System.Nullable<bool> value);
    partial void OnSTATUS_MAILChanged();
    partial void OnUPDATE_TIME_MAILChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_TIME_MAILChanged();
    #endregion
		
		public TRANG_THAI()
		{
			this._NOIDUNG_MAILs = new EntitySet<NOIDUNG_MAIL>(new Action<NOIDUNG_MAIL>(this.attach_NOIDUNG_MAILs), new Action<NOIDUNG_MAIL>(this.detach_NOIDUNG_MAILs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_TRANG_THAI", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_TRANG_THAI
		{
			get
			{
				return this._id_TRANG_THAI;
			}
			set
			{
				if ((this._id_TRANG_THAI != value))
				{
					this.Onid_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._id_TRANG_THAI = value;
					this.SendPropertyChanged("id_TRANG_THAI");
					this.Onid_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHDAU", DbType="Bit")]
		public System.Nullable<bool> DANHDAU
		{
			get
			{
				return this._DANHDAU;
			}
			set
			{
				if ((this._DANHDAU != value))
				{
					this.OnDANHDAUChanging(value);
					this.SendPropertyChanging();
					this._DANHDAU = value;
					this.SendPropertyChanged("DANHDAU");
					this.OnDANHDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XOATHU", DbType="Bit")]
		public System.Nullable<bool> XOATHU
		{
			get
			{
				return this._XOATHU;
			}
			set
			{
				if ((this._XOATHU != value))
				{
					this.OnXOATHUChanging(value);
					this.SendPropertyChanging();
					this._XOATHU = value;
					this.SendPropertyChanged("XOATHU");
					this.OnXOATHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_MAIL", DbType="Bit")]
		public System.Nullable<bool> STATUS_MAIL
		{
			get
			{
				return this._STATUS_MAIL;
			}
			set
			{
				if ((this._STATUS_MAIL != value))
				{
					this.OnSTATUS_MAILChanging(value);
					this.SendPropertyChanging();
					this._STATUS_MAIL = value;
					this.SendPropertyChanged("STATUS_MAIL");
					this.OnSTATUS_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_TIME_MAIL", DbType="Date")]
		public System.Nullable<System.DateTime> UPDATE_TIME_MAIL
		{
			get
			{
				return this._UPDATE_TIME_MAIL;
			}
			set
			{
				if ((this._UPDATE_TIME_MAIL != value))
				{
					this.OnUPDATE_TIME_MAILChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_TIME_MAIL = value;
					this.SendPropertyChanged("UPDATE_TIME_MAIL");
					this.OnUPDATE_TIME_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANG_THAI_NOIDUNG_MAIL", Storage="_NOIDUNG_MAILs", ThisKey="id", OtherKey="FK_id_TRANG_THAI")]
		public EntitySet<NOIDUNG_MAIL> NOIDUNG_MAILs
		{
			get
			{
				return this._NOIDUNG_MAILs;
			}
			set
			{
				this._NOIDUNG_MAILs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NOIDUNG_MAILs(NOIDUNG_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.TRANG_THAI = this;
		}
		
		private void detach_NOIDUNG_MAILs(NOIDUNG_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.TRANG_THAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHSACH_MAIL")]
	public partial class DANHSACH_MAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_DANHSACH_MAIL;
		
		private System.DateTime _THOIGIAN_GUI;
		
		private System.Nullable<int> _FK_id_MATKHAU_LOCAL;
		
		private System.Nullable<int> _FK_id_MATKHAU_MAIL;
		
		private System.Nullable<int> _FK_id_NOIDUNG_MAIL;
		
		private EntityRef<MATKHAU_LOCAL> _MATKHAU_LOCAL;
		
		private EntityRef<MATKHAU_MAIL> _MATKHAU_MAIL;
		
		private EntityRef<NOIDUNG_MAIL> _NOIDUNG_MAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_DANHSACH_MAILChanging(string value);
    partial void Onid_DANHSACH_MAILChanged();
    partial void OnTHOIGIAN_GUIChanging(System.DateTime value);
    partial void OnTHOIGIAN_GUIChanged();
    partial void OnFK_id_MATKHAU_LOCALChanging(System.Nullable<int> value);
    partial void OnFK_id_MATKHAU_LOCALChanged();
    partial void OnFK_id_MATKHAU_MAILChanging(System.Nullable<int> value);
    partial void OnFK_id_MATKHAU_MAILChanged();
    partial void OnFK_id_NOIDUNG_MAILChanging(System.Nullable<int> value);
    partial void OnFK_id_NOIDUNG_MAILChanged();
    #endregion
		
		public DANHSACH_MAIL()
		{
			this._MATKHAU_LOCAL = default(EntityRef<MATKHAU_LOCAL>);
			this._MATKHAU_MAIL = default(EntityRef<MATKHAU_MAIL>);
			this._NOIDUNG_MAIL = default(EntityRef<NOIDUNG_MAIL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_DANHSACH_MAIL", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_DANHSACH_MAIL
		{
			get
			{
				return this._id_DANHSACH_MAIL;
			}
			set
			{
				if ((this._id_DANHSACH_MAIL != value))
				{
					this.Onid_DANHSACH_MAILChanging(value);
					this.SendPropertyChanging();
					this._id_DANHSACH_MAIL = value;
					this.SendPropertyChanged("id_DANHSACH_MAIL");
					this.Onid_DANHSACH_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN_GUI", DbType="Date NOT NULL")]
		public System.DateTime THOIGIAN_GUI
		{
			get
			{
				return this._THOIGIAN_GUI;
			}
			set
			{
				if ((this._THOIGIAN_GUI != value))
				{
					this.OnTHOIGIAN_GUIChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN_GUI = value;
					this.SendPropertyChanged("THOIGIAN_GUI");
					this.OnTHOIGIAN_GUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_MATKHAU_LOCAL", DbType="Int")]
		public System.Nullable<int> FK_id_MATKHAU_LOCAL
		{
			get
			{
				return this._FK_id_MATKHAU_LOCAL;
			}
			set
			{
				if ((this._FK_id_MATKHAU_LOCAL != value))
				{
					if (this._MATKHAU_LOCAL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_MATKHAU_LOCALChanging(value);
					this.SendPropertyChanging();
					this._FK_id_MATKHAU_LOCAL = value;
					this.SendPropertyChanged("FK_id_MATKHAU_LOCAL");
					this.OnFK_id_MATKHAU_LOCALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_MATKHAU_MAIL", DbType="Int")]
		public System.Nullable<int> FK_id_MATKHAU_MAIL
		{
			get
			{
				return this._FK_id_MATKHAU_MAIL;
			}
			set
			{
				if ((this._FK_id_MATKHAU_MAIL != value))
				{
					if (this._MATKHAU_MAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_MATKHAU_MAILChanging(value);
					this.SendPropertyChanging();
					this._FK_id_MATKHAU_MAIL = value;
					this.SendPropertyChanged("FK_id_MATKHAU_MAIL");
					this.OnFK_id_MATKHAU_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_NOIDUNG_MAIL", DbType="Int")]
		public System.Nullable<int> FK_id_NOIDUNG_MAIL
		{
			get
			{
				return this._FK_id_NOIDUNG_MAIL;
			}
			set
			{
				if ((this._FK_id_NOIDUNG_MAIL != value))
				{
					if (this._NOIDUNG_MAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_NOIDUNG_MAILChanging(value);
					this.SendPropertyChanging();
					this._FK_id_NOIDUNG_MAIL = value;
					this.SendPropertyChanged("FK_id_NOIDUNG_MAIL");
					this.OnFK_id_NOIDUNG_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATKHAU_LOCAL_DANHSACH_MAIL", Storage="_MATKHAU_LOCAL", ThisKey="FK_id_MATKHAU_LOCAL", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public MATKHAU_LOCAL MATKHAU_LOCAL
		{
			get
			{
				return this._MATKHAU_LOCAL.Entity;
			}
			set
			{
				MATKHAU_LOCAL previousValue = this._MATKHAU_LOCAL.Entity;
				if (((previousValue != value) 
							|| (this._MATKHAU_LOCAL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATKHAU_LOCAL.Entity = null;
						previousValue.DANHSACH_MAILs.Remove(this);
					}
					this._MATKHAU_LOCAL.Entity = value;
					if ((value != null))
					{
						value.DANHSACH_MAILs.Add(this);
						this._FK_id_MATKHAU_LOCAL = value.id;
					}
					else
					{
						this._FK_id_MATKHAU_LOCAL = default(Nullable<int>);
					}
					this.SendPropertyChanged("MATKHAU_LOCAL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATKHAU_MAIL_DANHSACH_MAIL", Storage="_MATKHAU_MAIL", ThisKey="FK_id_MATKHAU_MAIL", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public MATKHAU_MAIL MATKHAU_MAIL
		{
			get
			{
				return this._MATKHAU_MAIL.Entity;
			}
			set
			{
				MATKHAU_MAIL previousValue = this._MATKHAU_MAIL.Entity;
				if (((previousValue != value) 
							|| (this._MATKHAU_MAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATKHAU_MAIL.Entity = null;
						previousValue.DANHSACH_MAILs.Remove(this);
					}
					this._MATKHAU_MAIL.Entity = value;
					if ((value != null))
					{
						value.DANHSACH_MAILs.Add(this);
						this._FK_id_MATKHAU_MAIL = value.id;
					}
					else
					{
						this._FK_id_MATKHAU_MAIL = default(Nullable<int>);
					}
					this.SendPropertyChanged("MATKHAU_MAIL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDUNG_MAIL_DANHSACH_MAIL", Storage="_NOIDUNG_MAIL", ThisKey="FK_id_NOIDUNG_MAIL", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public NOIDUNG_MAIL NOIDUNG_MAIL
		{
			get
			{
				return this._NOIDUNG_MAIL.Entity;
			}
			set
			{
				NOIDUNG_MAIL previousValue = this._NOIDUNG_MAIL.Entity;
				if (((previousValue != value) 
							|| (this._NOIDUNG_MAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NOIDUNG_MAIL.Entity = null;
						previousValue.DANHSACH_MAILs.Remove(this);
					}
					this._NOIDUNG_MAIL.Entity = value;
					if ((value != null))
					{
						value.DANHSACH_MAILs.Add(this);
						this._FK_id_NOIDUNG_MAIL = value.id;
					}
					else
					{
						this._FK_id_NOIDUNG_MAIL = default(Nullable<int>);
					}
					this.SendPropertyChanged("NOIDUNG_MAIL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOMAIN_MAIL")]
	public partial class DOMAIN_MAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_DOMAIN_MAIL;
		
		private string _DOMAIN;
		
		private int _PORT_MAIL;
		
		private EntitySet<MATKHAU_MAIL> _MATKHAU_MAILs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_DOMAIN_MAILChanging(string value);
    partial void Onid_DOMAIN_MAILChanged();
    partial void OnDOMAINChanging(string value);
    partial void OnDOMAINChanged();
    partial void OnPORT_MAILChanging(int value);
    partial void OnPORT_MAILChanged();
    #endregion
		
		public DOMAIN_MAIL()
		{
			this._MATKHAU_MAILs = new EntitySet<MATKHAU_MAIL>(new Action<MATKHAU_MAIL>(this.attach_MATKHAU_MAILs), new Action<MATKHAU_MAIL>(this.detach_MATKHAU_MAILs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_DOMAIN_MAIL", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_DOMAIN_MAIL
		{
			get
			{
				return this._id_DOMAIN_MAIL;
			}
			set
			{
				if ((this._id_DOMAIN_MAIL != value))
				{
					this.Onid_DOMAIN_MAILChanging(value);
					this.SendPropertyChanging();
					this._id_DOMAIN_MAIL = value;
					this.SendPropertyChanged("id_DOMAIN_MAIL");
					this.Onid_DOMAIN_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DOMAIN
		{
			get
			{
				return this._DOMAIN;
			}
			set
			{
				if ((this._DOMAIN != value))
				{
					this.OnDOMAINChanging(value);
					this.SendPropertyChanging();
					this._DOMAIN = value;
					this.SendPropertyChanged("DOMAIN");
					this.OnDOMAINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PORT_MAIL", DbType="Int NOT NULL")]
		public int PORT_MAIL
		{
			get
			{
				return this._PORT_MAIL;
			}
			set
			{
				if ((this._PORT_MAIL != value))
				{
					this.OnPORT_MAILChanging(value);
					this.SendPropertyChanging();
					this._PORT_MAIL = value;
					this.SendPropertyChanged("PORT_MAIL");
					this.OnPORT_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOMAIN_MAIL_MATKHAU_MAIL", Storage="_MATKHAU_MAILs", ThisKey="id", OtherKey="FK_id_DOMAIN_MAIL")]
		public EntitySet<MATKHAU_MAIL> MATKHAU_MAILs
		{
			get
			{
				return this._MATKHAU_MAILs;
			}
			set
			{
				this._MATKHAU_MAILs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MATKHAU_MAILs(MATKHAU_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.DOMAIN_MAIL = this;
		}
		
		private void detach_MATKHAU_MAILs(MATKHAU_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.DOMAIN_MAIL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATKHAU_LOCAL")]
	public partial class MATKHAU_LOCAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_MATKHAU_LOCAL;
		
		private string _USERNAME_LOCAL;
		
		private string _PASSWORD_LOCAL;
		
		private EntitySet<DANHSACH_MAIL> _DANHSACH_MAILs;
		
		private EntitySet<THONGTIN_CLIENT> _THONGTIN_CLIENTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_MATKHAU_LOCALChanging(string value);
    partial void Onid_MATKHAU_LOCALChanged();
    partial void OnUSERNAME_LOCALChanging(string value);
    partial void OnUSERNAME_LOCALChanged();
    partial void OnPASSWORD_LOCALChanging(string value);
    partial void OnPASSWORD_LOCALChanged();
    #endregion
		
		public MATKHAU_LOCAL()
		{
			this._DANHSACH_MAILs = new EntitySet<DANHSACH_MAIL>(new Action<DANHSACH_MAIL>(this.attach_DANHSACH_MAILs), new Action<DANHSACH_MAIL>(this.detach_DANHSACH_MAILs));
			this._THONGTIN_CLIENTs = new EntitySet<THONGTIN_CLIENT>(new Action<THONGTIN_CLIENT>(this.attach_THONGTIN_CLIENTs), new Action<THONGTIN_CLIENT>(this.detach_THONGTIN_CLIENTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_MATKHAU_LOCAL", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_MATKHAU_LOCAL
		{
			get
			{
				return this._id_MATKHAU_LOCAL;
			}
			set
			{
				if ((this._id_MATKHAU_LOCAL != value))
				{
					this.Onid_MATKHAU_LOCALChanging(value);
					this.SendPropertyChanging();
					this._id_MATKHAU_LOCAL = value;
					this.SendPropertyChanged("id_MATKHAU_LOCAL");
					this.Onid_MATKHAU_LOCALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME_LOCAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USERNAME_LOCAL
		{
			get
			{
				return this._USERNAME_LOCAL;
			}
			set
			{
				if ((this._USERNAME_LOCAL != value))
				{
					this.OnUSERNAME_LOCALChanging(value);
					this.SendPropertyChanging();
					this._USERNAME_LOCAL = value;
					this.SendPropertyChanged("USERNAME_LOCAL");
					this.OnUSERNAME_LOCALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_LOCAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD_LOCAL
		{
			get
			{
				return this._PASSWORD_LOCAL;
			}
			set
			{
				if ((this._PASSWORD_LOCAL != value))
				{
					this.OnPASSWORD_LOCALChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_LOCAL = value;
					this.SendPropertyChanged("PASSWORD_LOCAL");
					this.OnPASSWORD_LOCALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATKHAU_LOCAL_DANHSACH_MAIL", Storage="_DANHSACH_MAILs", ThisKey="id", OtherKey="FK_id_MATKHAU_LOCAL")]
		public EntitySet<DANHSACH_MAIL> DANHSACH_MAILs
		{
			get
			{
				return this._DANHSACH_MAILs;
			}
			set
			{
				this._DANHSACH_MAILs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATKHAU_LOCAL_THONGTIN_CLIENT", Storage="_THONGTIN_CLIENTs", ThisKey="id", OtherKey="FK_id_MATKHAU_LOCAL")]
		public EntitySet<THONGTIN_CLIENT> THONGTIN_CLIENTs
		{
			get
			{
				return this._THONGTIN_CLIENTs;
			}
			set
			{
				this._THONGTIN_CLIENTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACH_MAILs(DANHSACH_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.MATKHAU_LOCAL = this;
		}
		
		private void detach_DANHSACH_MAILs(DANHSACH_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.MATKHAU_LOCAL = null;
		}
		
		private void attach_THONGTIN_CLIENTs(THONGTIN_CLIENT entity)
		{
			this.SendPropertyChanging();
			entity.MATKHAU_LOCAL = this;
		}
		
		private void detach_THONGTIN_CLIENTs(THONGTIN_CLIENT entity)
		{
			this.SendPropertyChanging();
			entity.MATKHAU_LOCAL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATKHAU_MAIL")]
	public partial class MATKHAU_MAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_MATKHAU_MAIL;
		
		private string _USERNAME_MAIL;
		
		private string _PASSWORD_MAIL;
		
		private System.Nullable<int> _FK_id_DOMAIN_MAIL;
		
		private EntitySet<DANHSACH_MAIL> _DANHSACH_MAILs;
		
		private EntityRef<DOMAIN_MAIL> _DOMAIN_MAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_MATKHAU_MAILChanging(string value);
    partial void Onid_MATKHAU_MAILChanged();
    partial void OnUSERNAME_MAILChanging(string value);
    partial void OnUSERNAME_MAILChanged();
    partial void OnPASSWORD_MAILChanging(string value);
    partial void OnPASSWORD_MAILChanged();
    partial void OnFK_id_DOMAIN_MAILChanging(System.Nullable<int> value);
    partial void OnFK_id_DOMAIN_MAILChanged();
    #endregion
		
		public MATKHAU_MAIL()
		{
			this._DANHSACH_MAILs = new EntitySet<DANHSACH_MAIL>(new Action<DANHSACH_MAIL>(this.attach_DANHSACH_MAILs), new Action<DANHSACH_MAIL>(this.detach_DANHSACH_MAILs));
			this._DOMAIN_MAIL = default(EntityRef<DOMAIN_MAIL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_MATKHAU_MAIL", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_MATKHAU_MAIL
		{
			get
			{
				return this._id_MATKHAU_MAIL;
			}
			set
			{
				if ((this._id_MATKHAU_MAIL != value))
				{
					this.Onid_MATKHAU_MAILChanging(value);
					this.SendPropertyChanging();
					this._id_MATKHAU_MAIL = value;
					this.SendPropertyChanged("id_MATKHAU_MAIL");
					this.Onid_MATKHAU_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME_MAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USERNAME_MAIL
		{
			get
			{
				return this._USERNAME_MAIL;
			}
			set
			{
				if ((this._USERNAME_MAIL != value))
				{
					this.OnUSERNAME_MAILChanging(value);
					this.SendPropertyChanging();
					this._USERNAME_MAIL = value;
					this.SendPropertyChanged("USERNAME_MAIL");
					this.OnUSERNAME_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_MAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD_MAIL
		{
			get
			{
				return this._PASSWORD_MAIL;
			}
			set
			{
				if ((this._PASSWORD_MAIL != value))
				{
					this.OnPASSWORD_MAILChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_MAIL = value;
					this.SendPropertyChanged("PASSWORD_MAIL");
					this.OnPASSWORD_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_DOMAIN_MAIL", DbType="Int")]
		public System.Nullable<int> FK_id_DOMAIN_MAIL
		{
			get
			{
				return this._FK_id_DOMAIN_MAIL;
			}
			set
			{
				if ((this._FK_id_DOMAIN_MAIL != value))
				{
					if (this._DOMAIN_MAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_DOMAIN_MAILChanging(value);
					this.SendPropertyChanging();
					this._FK_id_DOMAIN_MAIL = value;
					this.SendPropertyChanged("FK_id_DOMAIN_MAIL");
					this.OnFK_id_DOMAIN_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATKHAU_MAIL_DANHSACH_MAIL", Storage="_DANHSACH_MAILs", ThisKey="id", OtherKey="FK_id_MATKHAU_MAIL")]
		public EntitySet<DANHSACH_MAIL> DANHSACH_MAILs
		{
			get
			{
				return this._DANHSACH_MAILs;
			}
			set
			{
				this._DANHSACH_MAILs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOMAIN_MAIL_MATKHAU_MAIL", Storage="_DOMAIN_MAIL", ThisKey="FK_id_DOMAIN_MAIL", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public DOMAIN_MAIL DOMAIN_MAIL
		{
			get
			{
				return this._DOMAIN_MAIL.Entity;
			}
			set
			{
				DOMAIN_MAIL previousValue = this._DOMAIN_MAIL.Entity;
				if (((previousValue != value) 
							|| (this._DOMAIN_MAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOMAIN_MAIL.Entity = null;
						previousValue.MATKHAU_MAILs.Remove(this);
					}
					this._DOMAIN_MAIL.Entity = value;
					if ((value != null))
					{
						value.MATKHAU_MAILs.Add(this);
						this._FK_id_DOMAIN_MAIL = value.id;
					}
					else
					{
						this._FK_id_DOMAIN_MAIL = default(Nullable<int>);
					}
					this.SendPropertyChanged("DOMAIN_MAIL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACH_MAILs(DANHSACH_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.MATKHAU_MAIL = this;
		}
		
		private void detach_DANHSACH_MAILs(DANHSACH_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.MATKHAU_MAIL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDUNG_MAIL")]
	public partial class NOIDUNG_MAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_NOIDUNG_MAIL;
		
		private string _TO_MAIL;
		
		private string _FROM_MAIL;
		
		private string _SUBJECT_MAIL;
		
		private string _CONTENT_MAIL;
		
		private System.Nullable<int> _FK_id_TRANG_THAI;
		
		private EntitySet<DANHSACH_MAIL> _DANHSACH_MAILs;
		
		private EntityRef<TRANG_THAI> _TRANG_THAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_NOIDUNG_MAILChanging(string value);
    partial void Onid_NOIDUNG_MAILChanged();
    partial void OnTO_MAILChanging(string value);
    partial void OnTO_MAILChanged();
    partial void OnFROM_MAILChanging(string value);
    partial void OnFROM_MAILChanged();
    partial void OnSUBJECT_MAILChanging(string value);
    partial void OnSUBJECT_MAILChanged();
    partial void OnCONTENT_MAILChanging(string value);
    partial void OnCONTENT_MAILChanged();
    partial void OnFK_id_TRANG_THAIChanging(System.Nullable<int> value);
    partial void OnFK_id_TRANG_THAIChanged();
    #endregion
		
		public NOIDUNG_MAIL()
		{
			this._DANHSACH_MAILs = new EntitySet<DANHSACH_MAIL>(new Action<DANHSACH_MAIL>(this.attach_DANHSACH_MAILs), new Action<DANHSACH_MAIL>(this.detach_DANHSACH_MAILs));
			this._TRANG_THAI = default(EntityRef<TRANG_THAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_NOIDUNG_MAIL", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_NOIDUNG_MAIL
		{
			get
			{
				return this._id_NOIDUNG_MAIL;
			}
			set
			{
				if ((this._id_NOIDUNG_MAIL != value))
				{
					this.Onid_NOIDUNG_MAILChanging(value);
					this.SendPropertyChanging();
					this._id_NOIDUNG_MAIL = value;
					this.SendPropertyChanged("id_NOIDUNG_MAIL");
					this.Onid_NOIDUNG_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_MAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TO_MAIL
		{
			get
			{
				return this._TO_MAIL;
			}
			set
			{
				if ((this._TO_MAIL != value))
				{
					this.OnTO_MAILChanging(value);
					this.SendPropertyChanging();
					this._TO_MAIL = value;
					this.SendPropertyChanged("TO_MAIL");
					this.OnTO_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_MAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FROM_MAIL
		{
			get
			{
				return this._FROM_MAIL;
			}
			set
			{
				if ((this._FROM_MAIL != value))
				{
					this.OnFROM_MAILChanging(value);
					this.SendPropertyChanging();
					this._FROM_MAIL = value;
					this.SendPropertyChanged("FROM_MAIL");
					this.OnFROM_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECT_MAIL", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string SUBJECT_MAIL
		{
			get
			{
				return this._SUBJECT_MAIL;
			}
			set
			{
				if ((this._SUBJECT_MAIL != value))
				{
					this.OnSUBJECT_MAILChanging(value);
					this.SendPropertyChanging();
					this._SUBJECT_MAIL = value;
					this.SendPropertyChanged("SUBJECT_MAIL");
					this.OnSUBJECT_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENT_MAIL", AutoSync=AutoSync.Always, DbType="VarChar(9)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string CONTENT_MAIL
		{
			get
			{
				return this._CONTENT_MAIL;
			}
			set
			{
				if ((this._CONTENT_MAIL != value))
				{
					this.OnCONTENT_MAILChanging(value);
					this.SendPropertyChanging();
					this._CONTENT_MAIL = value;
					this.SendPropertyChanged("CONTENT_MAIL");
					this.OnCONTENT_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_TRANG_THAI", DbType="Int")]
		public System.Nullable<int> FK_id_TRANG_THAI
		{
			get
			{
				return this._FK_id_TRANG_THAI;
			}
			set
			{
				if ((this._FK_id_TRANG_THAI != value))
				{
					if (this._TRANG_THAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._FK_id_TRANG_THAI = value;
					this.SendPropertyChanged("FK_id_TRANG_THAI");
					this.OnFK_id_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDUNG_MAIL_DANHSACH_MAIL", Storage="_DANHSACH_MAILs", ThisKey="id", OtherKey="FK_id_NOIDUNG_MAIL")]
		public EntitySet<DANHSACH_MAIL> DANHSACH_MAILs
		{
			get
			{
				return this._DANHSACH_MAILs;
			}
			set
			{
				this._DANHSACH_MAILs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANG_THAI_NOIDUNG_MAIL", Storage="_TRANG_THAI", ThisKey="FK_id_TRANG_THAI", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public TRANG_THAI TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI.Entity;
			}
			set
			{
				TRANG_THAI previousValue = this._TRANG_THAI.Entity;
				if (((previousValue != value) 
							|| (this._TRANG_THAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANG_THAI.Entity = null;
						previousValue.NOIDUNG_MAILs.Remove(this);
					}
					this._TRANG_THAI.Entity = value;
					if ((value != null))
					{
						value.NOIDUNG_MAILs.Add(this);
						this._FK_id_TRANG_THAI = value.id;
					}
					else
					{
						this._FK_id_TRANG_THAI = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRANG_THAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACH_MAILs(DANHSACH_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.NOIDUNG_MAIL = this;
		}
		
		private void detach_DANHSACH_MAILs(DANHSACH_MAIL entity)
		{
			this.SendPropertyChanging();
			entity.NOIDUNG_MAIL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTIN_CLIENT")]
	public partial class THONGTIN_CLIENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _id_KHACHHANG;
		
		private string _HO;
		
		private string _TEN;
		
		private string _EMAIL;
		
		private System.DateTime _NTNS;
		
		private System.Nullable<int> _GIOITINH;
		
		private System.DateTime _NGAYTAOTK;
		
		private int _MAPIN;
		
		private System.Nullable<int> _FK_id_MATKHAU_LOCAL;
		
		private EntityRef<MATKHAU_LOCAL> _MATKHAU_LOCAL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_KHACHHANGChanging(string value);
    partial void Onid_KHACHHANGChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNTNSChanging(System.DateTime value);
    partial void OnNTNSChanged();
    partial void OnGIOITINHChanging(System.Nullable<int> value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYTAOTKChanging(System.DateTime value);
    partial void OnNGAYTAOTKChanged();
    partial void OnMAPINChanging(int value);
    partial void OnMAPINChanged();
    partial void OnFK_id_MATKHAU_LOCALChanging(System.Nullable<int> value);
    partial void OnFK_id_MATKHAU_LOCALChanged();
    #endregion
		
		public THONGTIN_CLIENT()
		{
			this._MATKHAU_LOCAL = default(EntityRef<MATKHAU_LOCAL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_KHACHHANG", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string id_KHACHHANG
		{
			get
			{
				return this._id_KHACHHANG;
			}
			set
			{
				if ((this._id_KHACHHANG != value))
				{
					this.Onid_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._id_KHACHHANG = value;
					this.SendPropertyChanged("id_KHACHHANG");
					this.Onid_KHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NTNS", DbType="Date NOT NULL")]
		public System.DateTime NTNS
		{
			get
			{
				return this._NTNS;
			}
			set
			{
				if ((this._NTNS != value))
				{
					this.OnNTNSChanging(value);
					this.SendPropertyChanging();
					this._NTNS = value;
					this.SendPropertyChanged("NTNS");
					this.OnNTNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Int")]
		public System.Nullable<int> GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAOTK", DbType="Date NOT NULL")]
		public System.DateTime NGAYTAOTK
		{
			get
			{
				return this._NGAYTAOTK;
			}
			set
			{
				if ((this._NGAYTAOTK != value))
				{
					this.OnNGAYTAOTKChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAOTK = value;
					this.SendPropertyChanged("NGAYTAOTK");
					this.OnNGAYTAOTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPIN", DbType="Int NOT NULL")]
		public int MAPIN
		{
			get
			{
				return this._MAPIN;
			}
			set
			{
				if ((this._MAPIN != value))
				{
					this.OnMAPINChanging(value);
					this.SendPropertyChanging();
					this._MAPIN = value;
					this.SendPropertyChanged("MAPIN");
					this.OnMAPINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_MATKHAU_LOCAL", DbType="Int")]
		public System.Nullable<int> FK_id_MATKHAU_LOCAL
		{
			get
			{
				return this._FK_id_MATKHAU_LOCAL;
			}
			set
			{
				if ((this._FK_id_MATKHAU_LOCAL != value))
				{
					if (this._MATKHAU_LOCAL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_MATKHAU_LOCALChanging(value);
					this.SendPropertyChanging();
					this._FK_id_MATKHAU_LOCAL = value;
					this.SendPropertyChanged("FK_id_MATKHAU_LOCAL");
					this.OnFK_id_MATKHAU_LOCALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATKHAU_LOCAL_THONGTIN_CLIENT", Storage="_MATKHAU_LOCAL", ThisKey="FK_id_MATKHAU_LOCAL", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public MATKHAU_LOCAL MATKHAU_LOCAL
		{
			get
			{
				return this._MATKHAU_LOCAL.Entity;
			}
			set
			{
				MATKHAU_LOCAL previousValue = this._MATKHAU_LOCAL.Entity;
				if (((previousValue != value) 
							|| (this._MATKHAU_LOCAL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATKHAU_LOCAL.Entity = null;
						previousValue.THONGTIN_CLIENTs.Remove(this);
					}
					this._MATKHAU_LOCAL.Entity = value;
					if ((value != null))
					{
						value.THONGTIN_CLIENTs.Add(this);
						this._FK_id_MATKHAU_LOCAL = value.id;
					}
					else
					{
						this._FK_id_MATKHAU_LOCAL = default(Nullable<int>);
					}
					this.SendPropertyChanged("MATKHAU_LOCAL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
